### ISSUE TITLE
How to use this plugin in IDEA?

### ISSUE THREAD

**Issue by Jaylee89** [JAkutenshi/UMLDesignToolPluginProj#7]

**Comment by youbingchenyoubing** [comment]
the same question need help

**Comment by JAkutenshi** [comment]
Hi, This plugin, as you can see, had developed 2.5 years ago. 

So, I try to use it now and it's easy and little bit useless as well. I just open project from git example of java oop example: https://github.com/dollyaswin/java-oop

Next, after project creation install the plugin and restart IDEA. After that in the right edge of the screen happend "UML Design Tool Window" tag button. Click on it to open the plugin window.

![2019-01-16-214123_1600x900_scrot](https://user-images.githubusercontent.com/7635910/51271026-874acc80-19d7-11e9-953b-383355a604fc.png)

And all what you need is push the blue button "D+" for generation. Result is... as is:
![2019-01-16-214219_1600x900_scrot](https://user-images.githubusercontent.com/7635910/51271079-aa757c00-19d7-11e9-9147-ca0355601694.png)

Drag&Drop still works for me. Another buttons on menu panel is about zoom in/out/normal.

That is. Sorry for upsetting you, this project isn't so interesting for me now.

P.S.>
If you have no more questions next week-two, i'll close this issue.

Good luck
